---
execution_environments:
  - name: Windows EE
    image: docker.io/allensj/awx-ee-windows:latest
    pull: always
    description: "Custom PowerShell-enabled EE for Evaluate-STIG Windows deployments"
